# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Writeme < Formula
  desc "Cross-platform readme generator for your project"
  homepage "https://github.com/writeme-project/writeme"
  url "https://github.com/writeme-project/writeme/archive/v0.1.8.tar.gz"
  sha256 "6b3aadc40c6b2d93a01d7a20973406a17e53a33517f4750123adb5c58424ca0f"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/writeme-project/writeme/releases/download/v0.1.8/writeme-0.1.8-darwin-amd64.tar.gz"
      sha256 "6c3b9407c8adade62300a7bc7d6edb9bde96a076e61842bd53332631886da442"
    end

    on_arm do
      url "https://github.com/writeme-project/writeme/releases/download/v0.1.8/writeme-0.1.8-darwin-arm64.tar.gz"
      sha256 "e71c426863e3e91f3508e2075ce66f7c666c92f4d1a9348edd95134acc3802a9"
    end
  end

  def install
    bin.install "writeme"
  end
end
