# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Writeme < Formula
  desc "Cross-platform readme generator for your project"
  homepage "https://github.com/writeme-project/writeme"
  url "https://github.com/writeme-project/writeme/archive/v0.1.8.tar.gz"
  sha256 "6b3aadc40c6b2d93a01d7a20973406a17e53a33517f4750123adb5c58424ca0f"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/writeme-project/writeme/releases/download/v0.1.8/writeme-0.1.8-darwin-amd64.tar.gz"
      sha256 "692b77a5509a8bf52ce3b1d63d3c5c6d0f2639692fe9e716bb46b8fe8baba67a"
    end

    on_arm do
      url "https://github.com/writeme-project/writeme/releases/download/v0.1.8/writeme-0.1.8-darwin-arm64.tar.gz"
      sha256 "99d88e4525eaa2baa98e54ca837b4df26e1af2e5a487714ece89bd395292a50b"
    end
  end

  def install
    bin.install "writeme"
  end
end
